const mongoose = require("mongoose");
const connectDB = require("./config/db");
const Product = require("./models/productModel");

const products = [
  // ==================== TOYS ====================

  {
    id: 101,
    image: "https://loremflickr.com/600/600/toy?lock=101",
    name: "Colorful Building Blocks",
    brand: "Toyvora",
    category: "Toys",
    rating: 4.5,
    reviews: 120,
    originalPrice: 999,
    price: 699,
    discount: 30,
    offer: "30% OFF",
  },
  {
    id: 102,
    image: "https://loremflickr.com/600/600/toy?lock=102",
    name: "Cute Teddy Bear",
    brand: "Toyvora",
    category: "Toys",
    rating: 4.6,
    reviews: 150,
    originalPrice: 799,
    price: 599,
    discount: 25,
    offer: "25% OFF",
  },
  {
    id: 103,
    image: "https://loremflickr.com/600/600/toy?lock=103",
    name: "Kids Toy Car",
    brand: "FunKids",
    category: "Toys",
    rating: 4.4,
    reviews: 98,
    originalPrice: 899,
    price: 649,
    discount: 28,
    offer: "28% OFF",
  },
  {
    id: 104,
    image: "https://loremflickr.com/600/600/toy?lock=104",
    name: "Wooden Learning Toy",
    brand: "Kiddo",
    category: "Toys",
    rating: 4.7,
    reviews: 135,
    originalPrice: 1199,
    price: 899,
    discount: 25,
    offer: "25% OFF",
  },
  {
    id: 105,
    image: "https://loremflickr.com/600/600/toy?lock=105",
    name: "Soft Plush Toy",
    brand: "SoftJoy",
    category: "Toys",
    rating: 4.5,
    reviews: 110,
    originalPrice: 699,
    price: 499,
    discount: 29,
    offer: "29% OFF",
  },
  {
    id: 106,
    image: "https://loremflickr.com/600/600/toy?lock=106",
    name: "Toy Kitchen Set",
    brand: "PlayWorld",
    category: "Toys",
    rating: 4.6,
    reviews: 125,
    originalPrice: 1499,
    price: 999,
    discount: 33,
    offer: "33% OFF",
  },
  {
    id: 107,
    image: "https://loremflickr.com/600/600/toy?lock=107",
    name: "Mini Robot Toy",
    brand: "RoboKids",
    category: "Toys",
    rating: 4.3,
    reviews: 87,
    originalPrice: 1299,
    price: 899,
    discount: 31,
    offer: "31% OFF",
  },
  {
    id: 108,
    image: "https://loremflickr.com/600/600/toy?lock=108",
    name: "Color Puzzle Game",
    brand: "BrainFun",
    category: "Toys",
    rating: 4.5,
    reviews: 92,
    originalPrice: 599,
    price: 399,
    discount: 33,
    offer: "33% OFF",
  },
  {
    id: 109,
    image: "https://loremflickr.com/600/600/toy?lock=109",
    name: "Kids Musical Toy",
    brand: "MusicKids",
    category: "Toys",
    rating: 4.4,
    reviews: 105,
    originalPrice: 999,
    price: 699,
    discount: 30,
    offer: "30% OFF",
  },
  {
    id: 110,
    image: "https://loremflickr.com/600/600/toy?lock=110",
    name: "Colorful Toy Train Set",
    brand: "PlayWorld",
    category: "Toys",
    rating: 4.7,
    reviews: 140,
    originalPrice: 1599,
    price: 1099,
    discount: 31,
    offer: "31% OFF",
  },
  {
    id: 111,
    image: "https://loremflickr.com/600/600/toy?lock=111",
    name: "Cute Baby Doll",
    brand: "DollyLand",
    category: "Toys",
    rating: 4.5,
    reviews: 118,
    originalPrice: 899,
    price: 649,
    discount: 28,
    offer: "28% OFF",
  },
  {
    id: 112,
    image: "https://loremflickr.com/600/600/toy?lock=112",
    name: "Remote Control Car",
    brand: "SpeedKids",
    category: "Toys",
    rating: 4.6,
    reviews: 160,
    originalPrice: 1999,
    price: 1399,
    discount: 30,
    offer: "30% OFF",
  },
  {
    id: 113,
    image: "https://loremflickr.com/600/600/toy?lock=113",
    name: "Rainbow Plush Toy",
    brand: "SoftJoy",
    category: "Toys",
    rating: 4.5,
    reviews: 90,
    originalPrice: 799,
    price: 549,
    discount: 31,
    offer: "31% OFF",
  },
  {
    id: 114,
    image: "https://loremflickr.com/600/600/toy?lock=114",
    name: "Kids Learning Board",
    brand: "Kiddo",
    category: "Toys",
    rating: 4.7,
    reviews: 130,
    originalPrice: 999,
    price: 699,
    discount: 30,
    offer: "30% OFF",
  },
  {
    id: 115,
    image: "https://loremflickr.com/600/600/toy?lock=115",
    name: "Brain Puzzle Cube",
    brand: "BrainFun",
    category: "Toys",
    rating: 4.4,
    reviews: 82,
    originalPrice: 499,
    price: 349,
    discount: 30,
    offer: "30% OFF",
  },
  {
    id: 116,
    image: "https://loremflickr.com/600/600/toy?lock=116",
    name: "Kids Cooking Play Set",
    brand: "PlayWorld",
    category: "Toys",
    rating: 4.6,
    reviews: 115,
    originalPrice: 1299,
    price: 899,
    discount: 31,
    offer: "31% OFF",
  },
  {
    id: 117,
    image: "https://loremflickr.com/600/600/toy?lock=117",
    name: "Interactive Robot",
    brand: "RoboKids",
    category: "Toys",
    rating: 4.8,
    reviews: 175,
    originalPrice: 2499,
    price: 1799,
    discount: 28,
    offer: "28% OFF",
  },
  {
    id: 118,
    image: "https://loremflickr.com/600/600/toy?lock=118",
    name: "Creative Building Set",
    brand: "Toyvora",
    category: "Toys",
    rating: 4.7,
    reviews: 145,
    originalPrice: 1399,
    price: 999,
    discount: 29,
    offer: "29% OFF",
  },
  {
    id: 119,
    image: "https://loremflickr.com/600/600/toy?lock=119",
    name: "Racing Toy Car",
    brand: "SpeedKids",
    category: "Toys",
    rating: 4.5,
    reviews: 102,
    originalPrice: 1099,
    price: 749,
    discount: 32,
    offer: "32% OFF",
  },
  {
    id: 120,
    image: "https://loremflickr.com/600/600/toy?lock=120",
    name: "Large Teddy Bear",
    brand: "SoftJoy",
    category: "Toys",
    rating: 4.8,
    reviews: 190,
    originalPrice: 1799,
    price: 1299,
    discount: 28,
    offer: "28% OFF",
  },

  // ==================== ACCESSORIES ====================

  {
    id: 201,
    image: "https://loremflickr.com/600/600/gadget?lock=201",
    name: "Premium Smart Watch",
    brand: "TechPro",
    category: "Accessories",
    rating: 4.4,
    reviews: 100,
    originalPrice: 2999,
    price: 1999,
    discount: 33,
    offer: "33% OFF",
  },
  {
    id: 202,
    image: "https://loremflickr.com/600/600/gadget?lock=202",
    name: "Premium Phone Case",
    brand: "CasePro",
    category: "Accessories",
    rating: 4.3,
    reviews: 80,
    originalPrice: 699,
    price: 499,
    discount: 29,
    offer: "29% OFF",
  },
  {
    id: 203,
    image: "https://loremflickr.com/600/600/gadget?lock=203",
    name: "Fast Charging Power Bank",
    brand: "PowerMax",
    category: "Accessories",
    rating: 4.6,
    reviews: 145,
    originalPrice: 1999,
    price: 1399,
    discount: 30,
    offer: "30% OFF",
  },
  {
    id: 204,
    image: "https://loremflickr.com/600/600/gadget?lock=204",
    name: "USB-C Fast Charger",
    brand: "ChargePro",
    category: "Accessories",
    rating: 4.5,
    reviews: 120,
    originalPrice: 999,
    price: 699,
    discount: 30,
    offer: "30% OFF",
  },
  {
    id: 205,
    image: "https://loremflickr.com/600/600/gadget?lock=205",
    name: "Wireless Bluetooth Earbuds",
    brand: "SoundMax",
    category: "Accessories",
    rating: 4.7,
    reviews: 210,
    originalPrice: 2499,
    price: 1699,
    discount: 32,
    offer: "32% OFF",
  },
  {
    id: 206,
    image: "https://loremflickr.com/600/600/gadget?lock=206",
    name: "Wireless Gaming Mouse",
    brand: "GameTech",
    category: "Accessories",
    rating: 4.5,
    reviews: 135,
    originalPrice: 1599,
    price: 1099,
    discount: 31,
    offer: "31% OFF",
  },
  {
    id: 207,
    image: "https://loremflickr.com/600/600/gadget?lock=207",
    name: "Mechanical Gaming Keyboard",
    brand: "GameTech",
    category: "Accessories",
    rating: 4.8,
    reviews: 180,
    originalPrice: 2999,
    price: 2199,
    discount: 27,
    offer: "27% OFF",
  },
  {
    id: 208,
    image: "https://loremflickr.com/600/600/gadget?lock=208",
    name: "Wireless Phone Charger",
    brand: "ChargePro",
    category: "Accessories",
    rating: 4.4,
    reviews: 95,
    originalPrice: 1299,
    price: 899,
    discount: 31,
    offer: "31% OFF",
  },
  {
    id: 209,
    image: "https://loremflickr.com/600/600/gadget?lock=209",
    name: "Adjustable Phone Stand",
    brand: "DeskPro",
    category: "Accessories",
    rating: 4.3,
    reviews: 75,
    originalPrice: 599,
    price: 399,
    discount: 33,
    offer: "33% OFF",
  },
  {
    id: 210,
    image: "https://loremflickr.com/600/600/gadget?lock=210",
    name: "Braided USB Cable",
    brand: "CableMax",
    category: "Accessories",
    rating: 4.5,
    reviews: 110,
    originalPrice: 499,
    price: 299,
    discount: 40,
    offer: "40% OFF",
  },
  {
    id: 211,
    image: "https://loremflickr.com/600/600/gadget?lock=211",
    name: "Portable Bluetooth Speaker",
    brand: "SoundMax",
    category: "Accessories",
    rating: 4.6,
    reviews: 155,
    originalPrice: 1999,
    price: 1299,
    discount: 35,
    offer: "35% OFF",
  },
  {
    id: 212,
    image: "https://loremflickr.com/600/600/gadget?lock=212",
    name: "Premium Wireless Headphones",
    brand: "SoundMax",
    category: "Accessories",
    rating: 4.8,
    reviews: 230,
    originalPrice: 3999,
    price: 2799,
    discount: 30,
    offer: "30% OFF",
  },
  {
    id: 213,
    image: "https://loremflickr.com/600/600/gadget?lock=213",
    name: "Shockproof Mobile Cover",
    brand: "CasePro",
    category: "Accessories",
    rating: 4.4,
    reviews: 88,
    originalPrice: 799,
    price: 549,
    discount: 31,
    offer: "31% OFF",
  },
  {
    id: 214,
    image: "https://loremflickr.com/600/600/gadget?lock=214",
    name: "Laptop Sleeve Bag",
    brand: "DeskPro",
    category: "Accessories",
    rating: 4.6,
    reviews: 125,
    originalPrice: 1499,
    price: 999,
    discount: 33,
    offer: "33% OFF",
  },
  {
    id: 215,
    image: "https://loremflickr.com/600/600/gadget?lock=215",
    name: "Over-Ear Headphones",
    brand: "SoundMax",
    category: "Accessories",
    rating: 4.5,
    reviews: 140,
    originalPrice: 2999,
    price: 1999,
    discount: 33,
    offer: "33% OFF",
  },
  {
    id: 216,
    image: "https://loremflickr.com/600/600/gadget?lock=216",
    name: "Smart Fitness Band",
    brand: "TechPro",
    category: "Accessories",
    rating: 4.4,
    reviews: 105,
    originalPrice: 1999,
    price: 1299,
    discount: 35,
    offer: "35% OFF",
  },
  {
    id: 217,
    image: "https://loremflickr.com/600/600/gadget?lock=217",
    name: "Desktop Cable Organizer",
    brand: "DeskPro",
    category: "Accessories",
    rating: 4.2,
    reviews: 65,
    originalPrice: 499,
    price: 299,
    discount: 40,
    offer: "40% OFF",
  },
  {
    id: 218,
    image: "https://loremflickr.com/600/600/gadget?lock=218",
    name: "Foldable Tablet Stand",
    brand: "DeskPro",
    category: "Accessories",
    rating: 4.5,
    reviews: 90,
    originalPrice: 899,
    price: 599,
    discount: 33,
    offer: "33% OFF",
  },
  {
    id: 219,
    image: "https://loremflickr.com/600/600/gadget?lock=219",
    name: "USB Hub Adapter",
    brand: "TechPro",
    category: "Accessories",
    rating: 4.4,
    reviews: 100,
    originalPrice: 1299,
    price: 899,
    discount: 31,
    offer: "31% OFF",
  },
  {
    id: 220,
    image: "https://loremflickr.com/600/600/gadget?lock=220",
    name: "True Wireless Earbuds",
    brand: "SoundMax",
    category: "Accessories",
    rating: 4.7,
    reviews: 195,
    originalPrice: 2299,
    price: 1499,
    discount: 35,
    offer: "35% OFF",
  },
];

const seedProducts = async () => {
  try {
    await connectDB();

    await Product.deleteMany();

    await Product.insertMany(products);

    console.log("Products inserted successfully");

    await mongoose.connection.close();
  } catch (error) {
    console.log("Failed to insert products:", error.message);
  }
};

seedProducts();